# Generated by Django 4.2.3 on 2024-03-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address2',
        ),
    ]
